#!/bin/sh

set -e
set -x
if test -f Makefile; then
  make distclean
fi
rm -rf *~ *.cache *.m4 config.guess config.log config.status config.sub depcomp ltmain.sh

cp configure.ac configure.ac.orig
sed 's/^define(\[PACKAGE_SUFFIX\],\s*\[\(-[0-9a-zA-Z]*\)\])$/define(\[PACKAGE_SUFFIX\], \[~ci'$1'\])/g' configure.ac.orig > configure.ac
set +e
autoreconf --verbose --install --force
ERR=$?
set -e
mv configure.ac.orig configure.ac
exit $ERR
